In [1]:
# Numpy --> working with numeric data, while pandas for relational data

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)                    #for chaking version of numpy

1.24.3


In [4]:
# Zero dimensional arrary
import numpy as np

arr = np.array(42)

print(arr)

42


In [5]:
# One dimensional array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
# Two dimensional array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# Three dimensional array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
# ndim = for cheching number of dimensions it returns int value
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
# To Create an array with 5 dimensions and verify that it has 5 dimensions
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
# 1 D indexing 
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [11]:
# 2 D indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [12]:
# 3 D indexing
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [13]:
# Nevigating indexing 
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [14]:
# 1 D slicing of array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
print(arr[-3:-1])

[5 6]


In [16]:
print(arr[1:5:2])

[2 4]


In [17]:
# 2 D slicing of array
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [18]:
print(arr[0:2, 2])

[3 8]


In [19]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
# Data types 
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

#For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='S')                         #array with defined datatype 
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

int32
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [22]:
arr = np.array(['a', '2', '3'], dtype='i')                      # Error

ValueError: invalid literal for int() with base 10: 'a'

In [23]:
# The Difference Between Copy and View
"""
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
"""
import numpy as np

# Copy = deep copy (unchange)
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


# View = shallow copy (change)
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [25]:
# shape returns a tuple with each index having the number of corresponding elements
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)                             # return Rows and column

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [27]:
# Reshape From 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# Reshape From 1-D to 3-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)                 # Error

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [30]:
# Unknown Dimension
# Convert 1D array with 8 elements to 3D array with 2x2 elements

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# a multidimensional array into a 1D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)              

print(newarr)

[1 2 3 4 5 6]


In [32]:
# 1 D Arrays Iterating
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [33]:
# 2 D Arrays Iterating
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [35]:
# 3 D Arrays Iterating
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
# Iterating Arrays Using nditer()  ---> use for high dimensionas 
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [37]:
# Iterating With Different Step Size
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [38]:
# Enumerated Iteration Using ndenumerate()
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [39]:
# Joining NumPy Arrays
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [40]:
# axis=0 (Column-wise operation): Moves vertically (down).
# axis=1 (Row-wise operation): Moves horizontally (across).

# Join two 2-D arrays along rows (axis=1)
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
# Stacking Along Rows = hstack()
# number of column must be same 
import numpy as np

arr1 = np.array([[1, 1],
                [2, 2]])

arr2 = np.array([[3, 3],
                [4, 4]])

arr = np.hstack((arr1, arr2))

print(arr)

[[1 1 3 3]
 [2 2 4 4]]


In [49]:
# Stacking Along Columns = vstack()
# number of columns must be same
import numpy as np

arr1 = np.array([[1, 1],
                [2, 2]])

arr2 = np.array([[3, 3],
                [4, 4]])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [48]:
# Stacking Along Height (depth)
import numpy as np

arr1 = np.array([[1, 1],
                [2, 2]])

arr2 = np.array([[3, 3],
                [4, 4]])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 3]
  [1 3]]

 [[2 4]
  [2 4]]]


In [45]:
arr.shape

(1, 3, 2)

In [46]:
# Splitting NumPy Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [59]:
print(newarr[0]) # Access the splitted arrays
print(newarr[1]) # Access the splitted arrays

[1 2]
[3 4]


In [60]:
# Split the 2-D array into three 2-D arrays.
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [61]:
# An alternate solution is using hsplit() opposite of hstack()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Searching Arrays

In [62]:
# To search an array, use the where() method
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [63]:
#Search Sorted
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)          # Find the indexes where the value 7 should be inserted 

print(x)

1


In [64]:
x = np.searchsorted(arr, 7, side='right') # Find the indexes where the value 7 should be inserted, starting from the right

print(x)

2


In [65]:
# Find the indexes where the values 2, 4, and 6 should be inserted
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


NumPy Sorting Arrays

In [67]:
# The NumPy ndarray object has a function called sort(), that will sort a specified array
# This method returns a copy of the array, leaving the original array unchanged

import numpy as np

arr = np.array([3, 2, 0, 1])                                 #integer
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple'])                #string
print(np.sort(arr))

arr = np.array([True, False, True])                          #boolean 
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [68]:
# 2 D array sorting
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


NumPy Filter Array

In [1]:
# Filtering Arrays
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)  # the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


In [2]:
# Creating the Filter Array
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [3]:
# Creating Filter Directly From Array
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


Practice

In [51]:
bbb = np.arange(50).reshape(5,10)

In [52]:
bbb

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
bbb[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [54]:
Aone = np.array([1,2,3,4,11,78])

In [55]:
np.append(Aone,[11,12,13])  # add at last

array([ 1,  2,  3,  4, 11, 78, 11, 12, 13])

In [56]:
new_array = np.append([1,2,3],[11,12,13])    #without using np.array we can create array using append

In [57]:
print(new_array)

[ 1  2  3 11 12 13]


In [58]:
np.insert(Aone,0,100)      # insert at specific index

array([100,   1,   2,   3,   4,  11,  78])